export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  CONTACT: '/contact',
  PRODUCTS: '/products',
  SERVICES: '/services',
  CODING_CLASSES: '/coding-classes',
  PORTFOLIO: '/portfolio',
  CAREER: '/career',
  SUBSCRIPTION: '/subscription',
  USERS: '/users',
  ADMIN: {
    DASHBOARD: '/admin',
    USERS: '/admin/users',
    SAAS_CLIENTS: '/admin/saas-clients',
    SETTINGS: '/admin/settings',
    ANALYTICS: '/admin/analytics',
    PARTNERS: '/admin/partners',
    SUPPORT: '/admin/support',
    EMPLOYEE: '/admin/employee',
    COMPLIANCE: '/admin/compliance',
  },
  EMPLOYEE: {
    DASHBOARD: '/employee',
    TASKS: '/employee/tasks',
    TIMESHEET: '/employee/timesheet',
  },
  PARTNER: {
    DASHBOARD: '/partner',
    ORDERS: '/partner/orders',
    PAYOUTS: '/partner/payouts',
    LOGIN: '/partner/login',
    REGISTER: '/partner/register',
    LEADS: '/partner/leads',
    MARKETING: '/partner/marketing',
  },
  CUSTOMER: {
    DASHBOARD: '/customer',
    ORDERS: '/customer/orders',
    PROFILE: '/customer/profile',
  },
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
  },
}