export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  CONTACT: '/contact',
  PRODUCTS: '/products',
  SERVICES: '/services', // keep temporarily if needed or just rename it. Let's do the rename.
  CUSTOM_DEVELOPMENT: '/custom-development',
  SAAS_SOFTWARE: '/saas-software',
  DIGITAL_MARKETING: '/digital-marketing',
  DIGITAL_SIGNATURE: '/digital-signature',
  CODING_CLASSES: '/coding-classes',
  PORTFOLIO: '/portfolio',
  CAREER: '/career',
  USERS: '/users',
  ADMIN: {
    DASHBOARD: '/admin',
    USERS: '/admin/users',
    SAAS_CLIENTS: '/admin/saas-clients',
    PRODUCTS: '/admin/products',
    SETTINGS: '/admin/settings',
    ANALYTICS: '/admin/analytics',
    PARTNERS: '/admin/partners',
    SUPPORT: '/admin/support',
    EMPLOYEE: '/admin/employee',
    COMPLIANCE: '/admin/compliance',
  },
  EMPLOYEE: {
    DASHBOARD: '/employee',
    TASKS: '/employee/tasks',
    TIMESHEET: '/employee/timesheet',
    SUPPORT: '/employee/support',
  },
  PARTNER: {
    DASHBOARD: '/partner',
    ORDERS: '/partner/orders',
    PAYOUTS: '/partner/payouts',
    LOGIN: '/partner/login',
    REGISTER: '/partner/register',
    LEADS: '/partner/leads',
    MARKETING: '/partner/marketing',
    DUE_RENEWAL: '/partner/due-renewal',
    SUPPORT: '/partner/support',
  },
  CUSTOMER: {
    DASHBOARD: '/customer',
    ORDERS: '/customer/orders',
    PROFILE: '/customer/profile',
  },
  CLIENT: {
    LOGIN: '/client/login',
    PORTAL: '/client/portal',
    PROFILE: '/client/portal/profile',
    SUBSCRIPTION: '/client/portal/subscription',
    SUPPORT: '/client/portal/support',
    CUSTOMIZATION: '/client/portal/customization',
    ADDON_SERVICES: '/client/portal/addon-services',
  },
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
  },
  DEMO: {
    PORTAL: '/demo',
    SAAS_CLIENTS: '/demo/saas-clients',
    SUBSCRIPTION: '/demo/subscription',
    USERS: '/demo/users',
    ACCOUNTS: '/demo/accounts',
    EMPLOYEE: '/demo/employee',
    PROJECTS: '/demo/projects',
    COMPLIANCE: '/demo/compliance',
    PARTNERS: '/demo/partners',
    REPORTS: '/demo/reports',
    SUPPORT: '/demo/support',
    SETTINGS: '/demo/settings',
    PUNCH_IN: '/demo/punch-in',
  },
}